### ISSUE TITLE
Ask user confirmation at the beginning of package installation

### ISSUE THREAD

**Issue by lassoan** [KitwareMedical/SlicerNNUnet#1]
I was asked about installing PyTorch after several minutes being spent on installing other packages. This made the installation procedure much longer, because I left my computer when I saw that many Python packages are being installed and when I returned I've found that the installation was still not complete, because it required me to click OK on the popup to install Pytorch, and then it took several more minutes to install that, too.

To avoid user frustration, all necessary user confirmations should occur within seconds after `Install` button is clicked.

**Comment by Thibault-Pelletier** [comment]
@lassoan thanks for this issue!

I changed the logic so that confirmation is asked at the beginning of the process.
