### ISSUE TITLE
Make model path selection more robust

### ISSUE THREAD

**Issue by lassoan** [KitwareMedical/SlicerNNUnet#2]
I've provided `...\nnUNetTrainer__nnUNetPlans__3d_fullres\fold_0` as model path. Clicked Apply. Segmentation did not complete for several minutes. No error message was displayed in a popup or in the textbox below the button.

After several minutes I've checked the Python console and found errors:

```
Traceback (most recent call last):
  File "C:\D\SlicerNNUnet\SlicerNNUnet\SlicerNNUNetLib\SegmentationLogic.py", line 186, in _startInferenceProcess
    args = self._nnUNetParam.asArgList(self.nnUNetInDir, self.nnUNetOutDir)
  File "C:\D\SlicerNNUnet\SlicerNNUnet\SlicerNNUNetLib\Parameter.py", line 37, in asArgList
    raise RuntimeError(f"Invalid nnUNet configuration. {reason}")
RuntimeError: Invalid nnUNet configuration. Dataset.json file is missing. Provided model dir :
C:\Users\andra\OneDrive\Projects\SlicerNnUnet\nnUNetTrainer__nnUNetPlans__3d_fullres\fold_0
```

The error message should have been displayed in a popup.

Also, when choosing a folder that does not contain `dataset.json` then an error message should be displayed sooner (preferably immediately, but at least immediately after `Apply` is clicked).

**Comment by Thibault-Pelletier** [comment]
@lassoan thank you for this issue reporting! 

I changed the logic to be more robust and look for the dataset.json file in case a fold folder is provided. I also changed the ordering to check the parameters before trying to do any conversion.
