### ISSUE TITLE
Clicking Reload does not reload SlicerNNUNetLib

### ISSUE THREAD

**Issue by lassoan** [KitwareMedical/SlicerNNUnet#4]
It is very inconvenient to debug SlicerNNUnet module because you need to restart the application, load input data, etc. when scripts in SlicerNNUNetLib folders are changed. See an example how to reload a Python library [here](https://github.com/SlicerHeart/SlicerHeart/blob/afb9d94322d2be024afe8fa2c9f7223d49e1549b/ValveAnnulusAnalysis/ValveAnnulusAnalysis.py#L856-L871).

**Comment by Thibault-Pelletier** [comment]
Thank you for the link. I have implemented it.

Personally, I'm not a fan of the reloading. I usually do my testing / debug using Unit Tests and the PythonTestRunner module (by filtering the tests to run).

If you place the training weights in the `Testing/Data` folder, you should be able to run the `test_widget_can_run_nn_unet_segmentation_logic` integration test (see options below).

![image](https://github.com/KitwareMedical/SlicerNNUnet/assets/58782295/f2aa40c4-9936-4113-99de-59593d3baed8)

![image](https://github.com/KitwareMedical/SlicerNNUnet/assets/58782295/71f49553-389b-4a64-ab85-30f22d363184)

**Comment by lassoan** [comment]
Great, thank you!

If you only need to test some logic scripts in a separate executable then you can do away without reloading, but reloading is still needed for testing and troubleshooting of the full module.

I've noticed that you used `glob` for getting the filenames, which provides filenames in quasi random order. You need to reload files in the order based on their dependencies (starting with files that don't depend on others). If you reload files in different order then you usually need to reload several times until everything gets updated.

**Comment by Thibault-Pelletier** [comment]
Thank you for the feedback! I just changed the implementation to set the order by hand.
